### ISSUE TITLE
Making it work on already compiled binaries

### ISSUE THREAD

**Issue by ahmetb** [jondot/goweight#14]
I'm trying to use this for fairly complex projects like Kubernetes server components that are already pre-built.

Is it possible to make this work on compiled binaries like the blog post at https://science.raphael.poss.name/go-executable-size-visualization-with-d3.html explains?

**Comment by jondot** [comment]
No, sorry. Check the README and look for the blog post link - it explains how this tool works and what it requires - it hooks into the compilation process.

**Comment by ghost** [comment]
https://github.com/knz/go-binsize-viz worked for me!
