### ISSUE TITLE
Does this have to leave behind a binary?

### ISSUE THREAD

**Issue by BryanNoller** [jondot/goweight#3]
Does this have to leave behind a binary when used on a “package main” after execution has finished?

**Comment by jondot** [comment]
Not at all, it can clean it up. If you want to add this I’ll accept PR. Otherwise I’ll add this as a task and implement as time allows 
Thanks for the observation!

**Comment by BryanNoller** [comment]
I honestly haven't looked at the code yet, but it would be nice if possible to not write binary to disk in the first place, or write to a temporary file with a randomized unique name. Currently if you have a file in existence already, possibly unrelated to a compiled binary, it gets replaced.

**Comment by jondot** [comment]
Done! please take latest release :)
