### ISSUE TITLE
Doesn't work if there's more than one main() function

### ISSUE THREAD

**Issue by maddie** [jondot/goweight#7]
I know this shouldn't happen, but I have a helper program that builds my project for different GOOS/GOARCH concurrently that resides within the project, along with the `main.go`.

If I run `goweight`, it exits with:

```
2019/04/03 10:58:28 exit status 2
```

Maybe there should be some way to define which `.go` files should be used to compile, or to exclude?

**Comment by yeka** [comment]
#9  should help your issue.

**Comment by jondot** [comment]
Thanks all - merged and closing ❤️
