### ISSUE TITLE
How to handle projects created with gb package manager

### ISSUE THREAD

**Issue by kgrvamsi** [jondot/goweight#8]
I have a project created with gb pacakge manager and how can i execute the goweight command ?I see the following issue when i execute

```
# goweight
2019/04/04 18:12:17 exit status 1
```

**Comment by jondot** [comment]
Currently custom build / dep managers were not supported - but welcome to submit PR supporting your choice of package manager. 

If you can build using ‘go build’ then it should work and that’s what goweight does behind the scenes

**Comment by jondot** [comment]
Closing for now but reopen if you discover new information we should consider
